grid_fill = [
    ["C", "A", "R", "O", "B", " ", "G", "A", "S", "H", " ", "I", "Z", "O", "D"],
    ["A", "S", "I", "D", "E", " ", "E", "M", "M", "A", " ", "L", "I", "R", "A"],
    ["B", "I", "P", "O", "D", " ", "N", "E", "U", "R", "O", "L", "O", "G", "Y"],
    ["O", "P", "E", "R", "A", "S", "I", "N", "G", "E", "R", "S", " ", " ", " "],
    [" ", " ", " ", "L", "U", "K", "A", " ", " ", " ", "C", "A", "R", "T", "A"],
    ["B", "A", "S", "E", "B", "A", "L", "L", "P", "L", "A", "Y", "E", "R", "S"],
    ["I", "P", "A", "S", "S", " ", " ", "I", "R", "E", "S", " ", "C", "I", "S"],
    ["G", "E", "M", "S", " ", "V", "A", "M", "O", "S", " ", "M", "O", "P", "E"],
    ["A", "M", "P", " ", "A", "M", "S", "O", " ", " ", "D", "E", "A", "L", "S"],
    ["S", "A", "L", "E", "S", "A", "S", "S", "O", "C", "I", "A", "T", "E", "S"],
    ["K", "N", "E", "L", "T", " ", " ", " ", "P", "H", "A", "T", " ", " ", " "],
    [" ", " ", " ", "P", "I", "T", "C", "H", "P", "E", "R", "F", "E", "C", "T"],
    ["A", "L", "F", "A", "R", "O", "M", "E", "O", " ", "I", "R", "A", "N", "I"],
    ["W", "I", "I", "S", " ", "R", "O", "W", "S", " ", "S", "E", "R", "U", "M"],
    ["W", "E", "G", "O", " ", "A", "N", "N", "E", " ", "T", "E", "S", "T", "S"],
]

across_clues = [
    "ACROSS",
    "\n",
    "1. Cocoa alternative",
    "6. Big open cut",
    "10. Former partner of Lacoste",
    "14. Ferris Bueller talking directly to the audience, e.g.",
    '15. "Cruella" star Stone or Thompson',
    "16. Currency of Turkey",
    "17. Two-legged stand",
    "18. Branch of medicine concerned with the nervous system",
    "20. Some can break a glass with just their voice by reaching 100 decibels!",
    "22. Dončić of the Dallas Mavericks",
    "23. Magna ___",
    "27. Some can throw over 100mph!",
    "33. Skip me",
    "34. Makes angry",
    "35. Counterpart of trans, in gender terminology",
    "36. Ruby, Saphire, and Emerald",
    "37. 51-Down in Spanish",
    "39. Brood",
    "40. Electric guitar extension",
    '41. Playground retort to "Are not"',
    "42. Hands out cards",
    "43. Some can hit 100 percent of their quota!",
    "47. Prepared to propose, maybe",
    "48. '90s slang for cool",
    "49. 2012 Anna Kendrick movie...or possible praise for 20, 27, & 43-Across",
    "56. Italian car manufacturer that is also two letters of the NATO alphabet",
    "59. Like someone from Tehran",
    "60. Nintendo consoles released in 2006",
    "61. Operates a crew boat",
    "62. Clear part of blood",
    '63. "Here ___" (Time to start)',
    "64. Orphan who works at Green Gables",
    '65. They may say "See me"',
]

down_clues = [
    "DOWN",
    "\n",
    "1. Popular vacation destination in Mexico",
    '2. "Have ___" (Try some)',
    "3. Ready, as fruit",
    "4. Like carbon monoxide",
    "5. Smears with a sticky substance",
    "6. Amiable",
    '7. "I heard that!"',
    "8. Arrogant",
    "9. Favorite to win in an Aesop fable",
    '10. "You\'re not kidding"',
    "11. Uncle, in Italian",
    "12. Email ender for many charities",
    "13. Word with trip or spa",
    "19. Killer whales",
    "21. Jamaican genre",
    "24. Add another layer of paint",
    "25. Three-bagger in baseball",
    "26. Analyze",
    "27. Huge favor",
    "28. Supposed missing link between primates and homo sapiens",
    "29. Cube of cheese on a toothpick, maybe",
    "30. Vehicles that might have cans dragging from them",
    "31. Word with iPhone and athlete",
    "32. ___ Míserables",
    "37. Award given by MTV to musicians",
    "38. Bozo",
    "39. Quality of an impossible burger",
    "41. Moving excitedly",
    "42. Anne Frank, for the most famous one",
    '44. Locale of the "Four Dead in Five Seconds" gunfight',
    "45. Stand against",
    '46. Michael of SNL\'s "Weekend Update"',
    "50. ___ Bora (Rhyming region of Afghanistan)",
    "51. 37-Across in English",
    "52. Chopped with an axe",
    "53. Places to find hammers, anvils, and stirrups",
    "54. Former rules of England whose name sounds like a bolt fastener",
    "55. Burton and Allen, for two",
    "56. Response to a photo of a puppy, perhaps",
    "57. Word often confused with lay",
    "58. Newton's predecessor?",
]
